### ISSUE TITLE
duplicate behaviour

### ISSUE THREAD

**Issue by job** [pierky/bgp-large-communities-playground#3]
I disagree, the duplication test is not outdated, the -02 spec says:

```
Duplicate Large Communities SHOULD NOT be transmitted.  A receiving
speaker SHOULD silently remove duplicate Large Communities from a BGP
UPDATE message.
```

**Comment by pierky** [comment]
That is covered in the previous bullet, "Duplicate Large Communities not transmitted". The outdated test was meant for the following -01, Section 6 statement...

> A receiving speaker MUST NOT consider duplicate Large Communities
>    attributes in a BGP UPDATE message to be malformed.

... which has been removed from -02.

Does this close this issue? Do you thing a better phrasing could make it more clear?

**Comment by job** [comment]
Maybe add a test item "silently remove duplicate Large Communities"?
